### ISSUE TITLE
Time array type byval serialization problem

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#1027]
Introduced in this PR: https://github.com/Azure/autorest.go/pull/986.
In ser/deser mehtod, `time.Time` type could not convert to `timeRFC3339` type directly (pointer in previous logic is ok).
![image](https://github.com/Azure/autorest.go/assets/1726438/de9bd5fd-fdbb-4df5-b4b8-e3aa58ca890a)

cc: @Alancere

**Comment by jhendrixMSFT** [comment]
Which code generation version are you using?  I noticed this recently and fixed it in https://github.com/Azure/autorest.go/pull/1017

**Comment by tadelesh** [comment]
It seems without `slice-elements-byval` flag, the marshal file is still trying to deal with val not pointer.
