### ISSUE TITLE
Discriminator handle problem in the converter of new code model

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#1028]
Package: sdk/resourcemanager/security/armsecurity
Error: 
![image](https://github.com/Azure/autorest.go/assets/1726438/f3f973bb-fcf5-42a1-a4ba-3d6f5664b691)

cc: @Alancere

**Comment by jhendrixMSFT** [comment]
This is a bug in M4, see https://github.com/Azure/autorest/issues/4670

**Comment by tadelesh** [comment]
Is it the problem introduced after the new code mode? The previous released generated code is good though it seems the model in the error message is not generated as discriminated model.

**Comment by jhendrixMSFT** [comment]
The generated type wouldn't be usable though as it doesn't implement the discriminator interface.  In fact, it looks like all of the generated code for these polymorphic types is broken (i.e. there's no interface type for the hierarchy).
