### ISSUE TITLE
How to use `typespec.go`

### ISSUE THREAD

**Issue by petrkotas** [Azure/autorest.go#1167]
Hi, for the development of the new RP, we are using typespec to create the ARM API, which we need to also consume and produce in our code. For the code we use Golang. Currently we are writing the structures manually, however I see there is the package for typespec.go https://github.com/Azure/autorest.go/tree/main/packages/typespec-go present in the codebase. How do I use it?
I searched the npm, but without any luck. There is the distribution for python https://www.npmjs.com/package/@azure-tools/typespec-python but not for golang. 

Thank you.

**Comment by jhendrixMSFT** [comment]
The dev releases of the `typespec-go` emitter aren't published to npmjs yet as it's still a work-in-progress. For now, you can grab the tarball from our github releases and install it manually. Here's the latest one.

https://github.com/Azure/autorest.go/releases/tag/v0.1.0-dev.2-20240417.1

Once installed, specify `@azure-tools/typespec-go` for the emitter.

If you run into any problems and/or bad codegen, please open issues here so we can get them fixed.
