### ISSUE TITLE
Vet error for new discriminator of union as enum

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#1206]
See [example](https://cadlplayground.z22.web.core.windows.net/?c=QGRpc2NyaW1pbmF0b3IoImtpbmQiKQ0KbW9kZWwgQmFzZSB7DQogIMQYOiBLaW5kDQp9DQoNCnVuaW9uxRHGISJhIizFCGLHCGPGCHN0cmluZ8c1xlZLIGV4dGVuZHPRYCJrxjVuYW1lOsc7LA0KfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D).
The discriminator models will be generated something like:
```go
type Base struct {
    Kind: *Kind
}

type K struct {
    Kind *string
    Name *string
}

func (p *K) GetBase() *Base{
    return &Base{
        Kind: p.Kind,
    }
}
```
Since the kind is an open enum, it is possible that the model's kind property has a name not in the enum value list, which means the discriminator property type should not be the enum type.

**Comment by jhendrixMSFT** [comment]
This is how extensible enums works. Any value not in the list can still be supported via a cast. It's unclear why we'd change it at this point, can you clarify?

**Comment by tadelesh** [comment]
Pending on final decision of open/close enum of TypeSpec.

**Comment by tadelesh** [comment]
should be fixed tcgc
