### ISSUE TITLE
client_factory.go renamed to client.go

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1213]
The `client.go` generated by typespec-go seems to have the same functionality as `client_factory.go`
![image](https://github.com/Azure/autorest.go/assets/46921893/d1008c77-47a5-444e-a465-170f0e28a2f9)

**Comment by jhendrixMSFT** [comment]
This uses the modeled hierarchical client defined in the tsp. We could consider renaming this to `ClientFactory`. Can that be done in a `client.tsp` file for Go?

**Comment by tadelesh** [comment]
Redesign the logic for TypeSpec as it has pure client hierarchy. Use `@clientName` to rename the namespace to keep backward compatibility.

**Comment by tadelesh** [comment]
Need further discussion:
how go deal with naming collision with client and subclient?
tcgc is forced client name ends with `Cleint` which makes it impossible to rename in `client.tsp`
