### ISSUE TITLE
type name conflict

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1215]
typespec: https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/solarwinds/SolarWinds.Management
Error: type `SolarWindsOrganizationProperties` was renamed to `OrganizationProperties` which collides with an existing type name
![image](https://github.com/Azure/autorest.go/assets/46921893/8531964d-9ddf-42a0-bb15-7e2b5268cd19)

**Comment by jhendrixMSFT** [comment]
This is the same behavior as the autorest emitter. If stuttering renames result in a name collision, the emitter will fail (we don't guess for type names). What's the process for specifying a custom type name in tsp, do we need a decorator in `client.tsp`?

**Comment by tadelesh** [comment]
Rename the model in `client.tsp`.

**Comment by Alancere** [comment]
Add [client.tsp](https://github.com/Azure/azure-rest-api-specs-pr/pull/17746/commits/e010056f5e8e38d5c52d84f0288c3408a0ad22d8#diff-d12d82a87a6a544e59dcfc507c6ebdac37c5451998fd38a480e6334d489b8588) renamed
