### ISSUE TITLE
type redeclared

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1216]
typespec: https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/mission/Mission.Management
![image](https://github.com/Azure/autorest.go/assets/46921893/8d5d45a5-740a-4c9c-9cb8-c671687ffb8b)

**Comment by jhendrixMSFT** [comment]
This appears to be a bug in tcgc. There are two model entries for `BlobCatalog`.

**Comment by tadelesh** [comment]
@jhendrixMSFT from python emitter, i could only find one `BlobCatalog` model:
![image](https://github.com/Azure/autorest.go/assets/1726438/19f39102-24d4-4ff2-8638-13873147e99e)

**Comment by jhendrixMSFT** [comment]
Which tcgc version are you using?
