### ISSUE TITLE
populateAny

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1218]
typespec: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apicenter/ApiCenter.Management

It used to be `populateAny`, but now it's `populate`
![image](https://github.com/Azure/autorest.go/assets/46921893/ec2c7719-a72d-47fc-8e6c-76146ab22d53)

**Comment by jhendrixMSFT** [comment]
This is the same issue as https://github.com/Azure/autorest.go/issues/1221.
