### ISSUE TITLE
populateDateTimeRFC3339

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1219]
typespec: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apicenter/ApiCenter.Management

It used to be `populateDateTimeRFC3339`, but now it's `populateDateType`
![image](https://github.com/Azure/autorest.go/assets/46921893/c256ca89-36f9-429a-a30c-51f0dcbb4a0b)

**Comment by jhendrixMSFT** [comment]
Where is the definition for `SystemData`?

**Comment by tadelesh** [comment]
Should be the issue of TypeSpec ARM template. https://github.com/Azure/typespec-azure/issues/679
