### ISSUE TITLE
Handling of empty objects

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1221]
typespec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apicenter/ApiCenter.Management/models.tsp#L492

![image](https://github.com/Azure/autorest.go/assets/46921893/b786d2a9-31f7-4129-8a1b-d5a5a7149789)

swagger:
```
    "CustomProperties": {
      "type": "object",
      "description": "The custom metadata defined for API catalog entities."
    },
```

tsp:
```
@summary("Custom Properties")
@doc("The custom metadata defined for API catalog entities.")
model CustomProperties {}
```

**Comment by jhendrixMSFT** [comment]
Can you confirm that an empty object is the proper tsp to model `any`?

**Comment by jhendrixMSFT** [comment]
If name is generated and has no properties then it's an `any` type.

**Comment by tadelesh** [comment]
It should be the tsp definition issue.
