### ISSUE TITLE
type redeclared

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1304]
TypeSpec compiler v0.55.0
typespec-go: https://github.com/Azure/autorest.go/blob/main/packages/typespec-go/package.json#L69

1. scvmm\ScVmm.Management
    - typespec: https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/scvmm/ScVmm.Management/models.tsp#L37
    - ![image](https://github.com/Azure/autorest.go/assets/46921893/bebcd63b-c7ba-4e04-a5be-762dd38f4297)

2. relationships\Relationships.Management
    - typespec: https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/relationships/Relationships.Management/main.tsp#L39
    
    - ![image](https://github.com/Azure/autorest.go/assets/46921893/8d144e94-e60f-473e-9af7-afb3d1ee357a)

**Comment by Alancere** [comment]
It's different from https://github.com/Azure/autorest.go/issues/1216

**Comment by jhendrixMSFT** [comment]
In both cases there are two entries in `experimenal_sdkPackage.enums` and `experimenal_sdkPackage.models` respectively.
