### ISSUE TITLE
Unreferenced Types

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1323]
Generate unreferenced types such as `TrackedResourceBase`, `ArmResource`, `ArmResourceBase`

![image](https://github.com/Azure/autorest.go/assets/46921893/c3600c68-af6a-4549-a2f1-cfc815179e9e)

![image](https://github.com/Azure/autorest.go/assets/46921893/060ac186-8f2c-4cae-8cbf-25ecad30de50)

**Comment by jhendrixMSFT** [comment]
This will be fixed in `0.1.0-dev.3` of the emitter. Note that it will require setting option `remove-unreferenced-types` to `true`.
