### ISSUE TITLE
operations client list operation

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1330]
tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/standbypool/StandbyPool.Management/service.tsp#L35

- The OperationsClient has a subscriptionID attribute
![image](https://github.com/Azure/autorest.go/assets/46921893/1970dc76-0a4b-4ae9-a054-181ea05f32d4)

- operations list response is `PagedOperation`
![image](https://github.com/Azure/autorest.go/assets/46921893/92f6a1d4-95e9-4849-8484-03ba81aaa8ca)

**Comment by jhendrixMSFT** [comment]
This was a bug in tcgc, fixed via https://github.com/Azure/typespec-azure/pull/788 and in the `dev.3` version of the emitter.

**Comment by Alancere** [comment]
Hi @jhendrixMSFT, the `OperationsClient` mentioned above has an additional `subscriptionID` attribute, which seems to have not been fixed

```
"@azure-tools/typespec-client-generator-core": "0.42.3"
```

**Comment by jhendrixMSFT** [comment]
Are you saying you're changing the tcgc version from the one the emitter is using? If so, please don't do that. We pin to a specific version, and it should never be changed outside of the emitter.

**Comment by jhendrixMSFT** [comment]
Ok I understand the issue now, we shouldn't be propagating `subscriptionID` to this specific client.

The difference in `OperationListResult` vs `PagedOperation`, this comes from the tsp authoring.
