### ISSUE TITLE
Enum type assignment in `MarshalJson`

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1343]
tsp: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devopsinfrastructure/Microsoft.DevOpsInfrastructure

![image](https://github.com/Azure/autorest.go/assets/46921893/231f17ca-0b59-40af-8a1b-45852ec26569)

![image](https://github.com/Azure/autorest.go/assets/46921893/3efcbaf5-7ef2-4398-aac2-b9c67474f8c1)

**Comment by jhendrixMSFT** [comment]
I believe this is because tcgc is modeling the discriminator field in sub-types as the enum's underlying type.

Somewhat related to https://github.com/Azure/autorest.go/issues/1206

**Comment by tadelesh** [comment]
same issue to #1206.
