### ISSUE TITLE
discrimination kind comment

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1352]
tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devopsinfrastructure/Microsoft.DevOpsInfrastructure/main.tsp#L290

![image](https://github.com/Azure/autorest.go/assets/46921893/889544da-b39a-498e-b804-f6427d71d111)

**Comment by jhendrixMSFT** [comment]
I assume this is a diff between the tsp and OpenAPI versions. If so, then this appears to be expected as the inputs are slightly different. i.e. for the tsp, there is no doc comment for the discriminator property. There is one for the OpenAPI version though.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devopsinfrastructure/resource-manager/Microsoft.DevOpsInfrastructure/preview/2024-04-04-preview/devopsinfrastructure.json#L630

Please reopen if I misunderstood.
