### ISSUE TITLE
empty options replaced to `_`

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1353]
When using `autorest.go` to generate go sdk, should it also be replaced with `_`?

![image](https://github.com/Azure/autorest.go/assets/46921893/46b4dfef-5a0e-4b5a-851c-08e3bbb30c6f)

**Comment by jhendrixMSFT** [comment]
The change was made in https://github.com/Azure/autorest.go/pull/1331 and applies to both code generators. We just haven't released an updated version of `autorest.go` with the change.
