### ISSUE TITLE
Wrong client name

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1359]
tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communitytraining/Community.Management/main.tsp

![image](https://github.com/Azure/autorest.go/assets/46921893/655f9b12-54eb-4324-bbd3-e1a1132a8ecd)

**Comment by jhendrixMSFT** [comment]
The names aren't wrong per se as they come from the hierarchical client specified in the tsp (the names aren't great though).

Can you please clarify what was the expectation?

**Comment by Alancere** [comment]
> The names aren't wrong per se as they come from the hierarchical client specified in the tsp (the names aren't great though).
> 
> Can you please clarify what was the expectation?

Expected to be consistent with the go sdk generated by autorest.go.
![image](https://github.com/Azure/autorest.go/assets/46921893/fd44ed47-8243-4216-8c89-9c83f58610c5)

The operationId of spec swagger is as follows:
![image](https://github.com/Azure/autorest.go/assets/46921893/6f283ad4-bf3b-4fb6-b89a-501cde44e90d)

**Comment by jhendrixMSFT** [comment]
CC @tadelesh

**Comment by jhendrixMSFT** [comment]
Hmm, maybe it's the case that since the emitter turns off hierarchical clients for ARM, we also turn off hierarchical client naming for ARM too (assuming the tsp is correct).

**Comment by tadelesh** [comment]
is that name from `{rootClientName}{subClientName}`?
