### ISSUE TITLE
missing response body

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1360]
tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databasewatcher/DatabaseWatcher.Management/watcher.tsp#L126

![image](https://github.com/Azure/autorest.go/assets/46921893/dc163e64-3bc4-4724-92b2-18795aabcdfb)

**Comment by jhendrixMSFT** [comment]
This is coming from tcgc, the SdkMethod doesn't have a response type.

**Comment by tadelesh** [comment]
the root cause is the tsp does not define with the right custom lro.

**Comment by jhendrixMSFT** [comment]
@tadelesh so I can learn more about this, what should the definition look like?

**Comment by tadelesh** [comment]
```
start(
    ...ResourceInstanceParameters<Watcher>,
  ): ArmAcceptedLroResponse<ArmLroLocationHeader<LroHeaders=
  ArmLroLocationHeader<
    FinalResult=Watcher
  >>> | ArmResponse<Watcher> | ErrorResponse;
```
