### ISSUE TITLE
unhandled property kind `uri`

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1361]
tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurefleet/AzureFleet.Management/virtualMachineScaleSet.tsp#L58

![image](https://github.com/Azure/autorest.go/assets/46921893/2d229a5a-5a06-4fc7-9013-b712667d92ad)

**Comment by jhendrixMSFT** [comment]
Fixed.
