### ISSUE TITLE
Stutter enum type name

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1362]
`autorest.go` and `typespec-go` seem to handle enum stutter differently

tsp:  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databasewatcher/DatabaseWatcher.Management/watcher.tsp#L167

![image](https://github.com/Azure/autorest.go/assets/46921893/acf33ec7-f79c-4426-9b2c-5742d7a66fa8)

**Comment by jhendrixMSFT** [comment]
Added option `fix-const-stuttering`, off by default, to keep compat with autorest.go.
