### ISSUE TITLE
tsp codegen for examples is broken with latest tcgc

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#1441]
For reference https://github.com/Azure/typespec-azure/issues/1688

Also observed was some of the ARM modules have missing/incorrect parameters.

**Comment by jhendrixMSFT** [comment]
Also impacted is `armloadtestservice`.
```
vet.exe: .\zz_loadtests_client_example_test.go:25:105: not enough arguments in call to clientFactory.NewLoadTestsClient().BeginCreateOrUpdate
        have (context.Context, string, string, nil)
        want (context.Context, string, string, armloadtestservice.LoadTestResource, *armloadtestservice.LoadTestsClientBeginCreateOrUpdateOptions)
```

**Comment by jhendrixMSFT** [comment]
The api-version issue has been fixed.

**Comment by tadelesh** [comment]
confirmed that all the example failure is from setting body parameter name with `@encodedName`. open tcgc issue [here](https://github.com/Azure/typespec-azure/issues/1739).
