### ISSUE TITLE
Is there a way to override the "Base class" elimination but only for specific types

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/autorest.go#1466]
Event Grid system events uses the inheritance model in our TypeSpec models. typespec-go helpfully just removes those vestigial types, which is _great_, but sometimes you need to keep those types because they are actually models, not just composition types:

- [MediaJobOutputStateChangeEventData](https://github.com/Azure/azure-rest-api-specs/blob/5bd6dc6118d8bc231ecd913c2e67ff521cfd43b7/specification/eventgrid/Azure.Messaging.EventGrid.SystemEvents/Microsoft.Media/MediaServices.tsp#L200)
- [MediaJobStateChangeEventData](https://github.com/Azure/azure-rest-api-specs/blob/5bd6dc6118d8bc231ecd913c2e67ff521cfd43b7/specification/eventgrid/Azure.Messaging.EventGrid.SystemEvents/Microsoft.Media/MediaServices.tsp#L106)

This might just become a question with an easy answer (just decorate this with 'x'), but otherwise this is a bug. I have a workaround for now, where I literally just copied the old models over, but I'd love to remove those soon.

**Comment by tadelesh** [comment]
after this [pr](https://github.com/Azure/autorest.go/pull/1468) merge, you could use the new release to try with `@usage`.
