### ISSUE TITLE
Generator should error on malformed discriminator values

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.go#182]
Specification file: 
https://github.com/Azure/azure-rest-api-specs/blob/10d46b9f23e7367d9e63682b24c8a65513f436f4/specification/security/resource-manager/readme.md
Involved tags:
`package-composite-v1`, `package-composite-v2` and `package-composite-v3`
Suspected json file:
https://github.com/Azure/azure-rest-api-specs/blob/10d46b9f23e7367d9e63682b24c8a65513f436f4/specification/security/resource-manager/Microsoft.Security/preview/2019-01-01-preview/automations.json
Phenomenon:
The generated enums have duplicated values, for instance:
```
// ActionType enumerates the values for action type.
type ActionType string

const (
	// ActionTypeAutomationAction ...
	ActionTypeAutomationAction ActionType = "AutomationAction"
	// ActionTypeEventHub ...
	ActionTypeEventHub ActionType = "EventHub"
	// ActionTypeEventHub1 ...
	ActionTypeEventHub1 ActionType = "EventHub"
	// ActionTypeEventHub2 ...
	ActionTypeEventHub2 ActionType = "EventHub"
	// ActionTypeLogicApp ...
	ActionTypeLogicApp ActionType = "LogicApp"
	// ActionTypeLogicApp1 ...
	ActionTypeLogicApp1 ActionType = "LogicApp"
	// ActionTypeLogicApp2 ...
	ActionTypeLogicApp2 ActionType = "LogicApp"
	// ActionTypeWorkspace ...
	ActionTypeWorkspace ActionType = "Workspace"
)
```

The duplicated enums cause the unmarshal method has duplicated cases for enum variables, which is causing vet failure in go SDK ([here](https://github.com/Azure/azure-sdk-for-go/pull/6454)).
```
func unmarshalBasicAutomationActionLogicApp(body []byte) (BasicAutomationActionLogicApp, error) {
	var m map[string]interface{}
	err := json.Unmarshal(body, &m)
	if err != nil {
		return nil, err
	}

	switch m["actionType"] {
	case string(ActionTypeLogicApp):
		var aalai AutomationActionLogicAppInput
		err := json.Unmarshal(body, &aalai)
		return aalai, err
	case string(ActionTypeLogicApp):
		var aalao AutomationActionLogicAppOutput
		err := json.Unmarshal(body, &aalao)
		return aalao, err
	default:
		var aala AutomationActionLogicApp
		err := json.Unmarshal(body, &aala)
		return aala, err
	}
}
```

**Comment by jhendrixMSFT** [comment]
This is due to the swagger being malformed, i.e. each enum entry is duplicated.  We could update the generator to throw an exception in this case instead of generating bad code however that makes the priority lower.

**Comment by chamons** [comment]
I just tried reproducing this, and it appears autorest core now detects this malformed nature:

```
stderr: ERROR: Semantic violation: Discriminator must be a required property. (components > schemas > Setting)
  discriminator: { propertyName: 'kind' }
```

@jhendrixMSFT - I assume that makes this closable now?

**Comment by jhendrixMSFT** [comment]
Oh nice, glad to see they fixed this.  Thanks for validating will close.
