### ISSUE TITLE
Add reference samples for full body-complex swagger

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#206]
This includes references for the following groups: 
- Array
- Basic
- Dictionary
- Flatten
- Inheritance
- Polymorphic recursive
- Primitive
- Readonlyproperty

**Comment by catalinaperalta** [comment]
This as been added in part in the following PRs: #209 #204

**Comment by catalinaperalta** [comment]
Basic was completed in #209

**Comment by jhendrixMSFT** [comment]
This is mostly complete.  Flattening is not applicable and R/O is tracked in a separate issue.
