### ISSUE TITLE
String group acceptance test problems

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#243]
- GetBase64URLEncoded: returns an unmarshalling error. We need to add an unmarshal/marshal method on azcore.Response and azcore.Request. Also need to invoke these methods in codegen when working with base64 data. 
- PutBase64URLEncoded: same as GetBase64URLEncoded
- TestStringPutNull: pending query about whether PutNull should send null in the request body or send an undefined request body.

**Comment by jhendrixMSFT** [comment]
Fixed
