### ISSUE TITLE
Add testserver tests for initial codegen effort

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#252]
Add tests for all of the endpoints in the following groups of generated code: 

- [ ] AdditionalPropertiesGroup

- [x] BooleanGroup

- [x] ByteGroup

- [x] ComplexGroup

- [x] CustomBaseURLGroup

- [x] MoreCustomBaseURLGroup

- [x] NumberGroup

- [x] StringGroup

**Comment by catalinaperalta** [comment]
PENDING WORK FOR EACH OF THE GENERATED GROUPS:
- Complexgroup: 
1. Add tests for primitivegroup endpoints related to dates and time
2. Add tests for polymorphism
3. Add tests for polymorphic recursion
4. Add tests for flattenedmodels
5. Fix needed: Arraygroup needs to have an ArrayWrapper model that does not include the `omitempty` tag for the PutEmpty to be successful
6. Fix needed: Arraygroup ArrayWrapper needs to have Array field of type []*string
7. Fix needed: dictionarygroup needs to have a DictionaryWrapper without the `omitempty` tag
8. Fix needed: stringgroup needs to fix marshalling/unmarshalling for base64url data
9. Fix needed: stringgroup PutNull is not working
10. Fix needed: MoreCustomBaseURLGroup the endpoint being generated is static and doesn't dynamically add the variables send through the create method. 
11. Fix needed: AdditionalPropertiesGroup need to add secondary additional properties field.

**Comment by catalinaperalta** [comment]
cc @jhendrixMSFT just so you know I'm mainly adding pending work for the tests and fixes that we need here.

**Comment by jhendrixMSFT** [comment]
This is mostly done.  The problem with additionalProperties is tracked via a separate issue.
