### ISSUE TITLE
Nil values versus empty values implementation

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#255]
We need to determine whether nil values and empty values should be treated differently when unmarshalling the data received or sent to an endpoint. 

For instance, is it meaningful to receive a nil array vs an empty array or a nil dictionary vs an empty dictionary.

**Comment by jhendrixMSFT** [comment]
We must emit all fields as pointer-to-type to properly support this for things like slices and dictionaries.  The work is done so this should now be fixed.
