### ISSUE TITLE
Add custom marshalling for RO properties

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#259]
Related to complexgroup ReadOnlyProperty PutValid

**Comment by jhendrixMSFT** [comment]
We should implement this in such a way that it only takes effect when sending requests to the REST endpoint.  We've had several customers complain that their custom logging/caching/round-tripping of JSON data is broken due to R/O fields being omitted during marshalling.

**Comment by jhendrixMSFT** [comment]
https://gist.github.com/jhendrixMSFT/2340616d2583e853f3096e826953babb

**Comment by jhendrixMSFT** [comment]
Fixed.
