### ISSUE TITLE
Add support for duration format

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#270]
~1. ParamByte needs to use base64.STDEncoding.EncodeToString instead of just string cast~
~2. ParamExistingKey User-Agent header has been parsed and it shouldnt be, however even when the header is parsed correctly the request still fails.~
~3. ParamEnum doesn't pass in the null scenario~
4. All the time, date and duration TESTS and generated code PARSING need to be looked at, they are not being sent in the correct format. 
~5. ParamProtectedKey the contentType header is not being generated correctly since it was renamed.~
6. ParamString null scenario is broken
~7. All the response endpoints dont marshal the value returned into the response structs~

**Comment by catalinaperalta** [comment]
Bug 1, 2, 5 are resolved in this PR: #273

**Comment by jhendrixMSFT** [comment]
Repurposing this issue to track adding support for duration format (it was the only thing remaining for headergroup and is applicable to models as well).

**Comment by catalinaperalta** [comment]
As per offline discussion, durations are being left as strings.
