### ISSUE TITLE
[Track1] Generated code contains compilation errors of service `apimanagement` in the `Send` function

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.go#281]
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/95ff995a2d96e4777e69079526d639c2057f8852/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-01-01/apimusers.json#L662
(every api-version of apimanagement is reporting this error)
Part of the generated code: 
```go
// SendSender sends the Send request. The method will close the
// http.Response Body if it receives an error.
func (client UserConfirmationPasswordClient) SendSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}
```
`go vet` reports:
```
Not enough arguments in call to client.Send 
```
While it should be:
```go
// SendSender sends the Send request. The method will close the
// http.Response Body if it receives an error.
func (client UserConfirmationPasswordClient) SendSender(req *http.Request) (*http.Response, error) {
	return client.BaseClient.Client.Send(req, azure.DoRetryWithRegistration(client.Client))
}
```

Assumption:
Usually, a client does not have a method `Send`, then `client.Send` would be equivalent to `client.BaseClient.Client.Send`. But in this case, this client happens to have a method of `Send`, then the `client.Send` maps to its own `Send` instead of the `Send` function of `autorest.Client`

**Comment by jhendrixMSFT** [comment]
Fixed in generator version 2.1.143
