### ISSUE TITLE
Using api keys

### ISSUE THREAD

**Issue by devfd** [Azure/autorest.go#312]
hi,

I am trying to generate a go sdk against our api. The generated code does not seem to take into account the `security` definition. We have something similar in our swagger definition:
```securityDefinitions:
 XAccount:
    type: apiKey
    name: x-account
    in: header
    description: Requests should pass an x-account header.

security:
  - XAccount: []
```

Am I missing something ?

Many thanks

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

I assume you're using the generator in the `master` branch.  The way auth works is that you must set the `Client.Authorizer` field to the authorization type required by your service (key, oauth token, etc).  See the [Authorization](https://github.com/Azure/azure-sdk-for-go#authentication) section in the Azure SDK for Go for an example of how it works there.  We have various Authorizers in the [go-autorest](https://github.com/Azure/go-autorest) repo, maybe one of those will work?

**Comment by chamons** [comment]
Hey @devfd - Without the requested information, we're unable to help resolve this issue.

Please feel free to reopen with additional information or open a new issue in the future.
