### ISSUE TITLE
Missing query params in BlockBlob swagger

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#331]
comp and blockid query params are not in the swagger

**Comment by catalinaperalta** [comment]
Working with the comp query param will be determined pending discussions with the Storage team. 
BlockID was added to the swagger here: https://github.com/Azure/azure-rest-api-specs/pull/8926

**Comment by jhendrixMSFT** [comment]
This is a non-issue (see swagger PR for more info).
