### ISSUE TITLE
Swagger issue: BlobContentType is required not optional

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#333]
In AppendBlob_Create BlobContentType is required for a successful request but it is marked as optional

**Comment by jhendrixMSFT** [comment]
After some more fiddling I'm not sure this is true.  I think the request was failing for other reasons but I can't articulate what those reasons are yet.

**Comment by catalinaperalta** [comment]
Closing this, since it appears to not actually be required with the correct ContentLength being set.
