### ISSUE TITLE
Add stream bodies to generated response models

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#351]
This is debating if we want to add a `Body` field to the response envelope.  It would look something like this.
```go
type FooResponse struct {
    Body io.ReadCloser
    HeaderOne *string
    RawResponse *http.Response
}
```
For cases where there's a response body and header, there is at present no `Body` field in the response envelope so you have to know to access it via the `RawResponse`.  If there's no header (just body) then there's no response envelope, just the `*http.Response`.

**Comment by jhendrixMSFT** [comment]
Per discussion, we don't want to do this as it introduces two places to get the same data.
