### ISSUE TITLE
Check the following LRO tests behavior

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#374]
TestLROBeginPutNoHeaderInRetry
TestLROBeginPutNonResource
TestLROBeginPutSubResource

**Comment by catalinaperalta** [comment]
In lrosaDsOperations:
TestLROSADSBeginPut200InvalidJSON

**Comment by catalinaperalta** [comment]
Several tests referenced in the previous comment have been fixed with #390

**Comment by jhendrixMSFT** [comment]
For the original three tests cited when the issue was opened.  Per the test server and the track 1 implementation, the expectation is that `PollUntilDone()` will retry if there was an error (i.e. the first one not returning a body).

**Comment by jhendrixMSFT** [comment]
Per offline conversation I don't think we need to do anything here.  I believe these tests were invented to simulate failures that should trigger a retry.  Between our body download and retry policies we should already have the necessary retry logic in place.
