### ISSUE TITLE
Add testserver test to cover null nextlink case

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#408]
Test to cover null next link and no next link field on the model

**Comment by chamons** [comment]
@catalinaperalta - Is this issue still active? Could you provide a few more details if not, so i can take a look.

**Comment by jhendrixMSFT** [comment]
We have one [here](https://github.com/Azure/autorest.testserver/blob/main/swagger/paging.json#L39) and generate the correct code.
