### ISSUE TITLE
Check why some media tags are undefined

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.go#412]
Check lrogroup, paginggroup and azurespecialsgroup for these undefined tags.

**Comment by jhendrixMSFT** [comment]
The affected types aren't used as parameter or return values, so when we recursively add the marhsalling format they're skipped.  Should be able to apply the doc-level produces/consumes to determine the marshalling format.

**Comment by jhendrixMSFT** [comment]
Dependent on https://github.com/Azure/perks/issues/108

**Comment by jhendrixMSFT** [comment]
We've implemented a work-around, the underlying issue is in perks.
