### ISSUE TITLE
[CosmosDB] Unable to generate go sdk from specifications in azure-rest-api-specs. Error: FATAL: System.ArgumentOutOfRangeException: Index was out of range.

### ISSUE THREAD

**Issue by MehaKaushik** [Azure/autorest.go#420]
CosmosDB specifications exist [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cosmos-db/resource-manager).
We created a PR to allow generation of SDK for GO [here](https://github.com/Azure/azure-rest-api-specs/pull/9793):.

Unfortunately, the autorest.go fails with the error: 
```
`specs/specification/cosmos-db/resource-manager/readme.md FATAL: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
[Azure/azure-sdk-for-go]Parameter name: startIndex
```
Detailed logs are [here]( https://sdkautomation.blob.core.windows.net/sdkautomation-pipeline/Azure/azure-rest-api-specs/9793/azure-sdk-for-go/logs.txt)

I tried generating the sdk locally as immediate solution, but the same issue persists. I am using AutoRest version 2.0.4413, Attached the screenshot for errors when attempted to run locally: 
![image](https://user-images.githubusercontent.com/11769687/84192109-61035200-aa4e-11ea-931a-e56a16216127.png)

**Comment by jhendrixMSFT** [comment]
This was due to an authoring error however maybe we can make the error message more actionable.  @ArcturusZhang if you have time.
