### ISSUE TITLE
Some enum types are generated as code name which might change between versions

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.go#571]
In the compute v0.1.0, it is generated with name [`Enum47`](https://github.com/Azure/azure-sdk-for-go/blob/809486c5504837c6090afaa187e5b200cf1aa3ce/sdk/arm/compute/2020-09-30/armcompute/zz_generated_enums.go#L487), but in compute v0.2.0, it is generated with name [`Enum48`](https://github.com/Azure/azure-sdk-for-go/blob/268147d542fc0a6101db6f2056fc7a4d43efaca3/sdk/arm/compute/2020-09-30/armcompute/zz_generated_enums.go#L507). 

This might cause unexpected major version bump. Swagger source of this example: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.ContainerService/stable/2017-01-31/containerService.json#L354

**Comment by jhendrixMSFT** [comment]
This might be an M4 bug, needs further investigation.

**Comment by ArcturusZhang** [comment]
My assumption is that this Enum is missing an `x-ms-enum` extension

**Comment by jhendrixMSFT** [comment]
I think you're right, all of these enums need an `x-msu-enum` annotation so the names are stable.  Can you please open an issue in the specs repo?  There's not much we can do about this from a codegen or M4 perspective (please reopen if you disagree).

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT shouldn't these Swaggers fail to generate without these required attributes being set?

**Comment by jhendrixMSFT** [comment]
Unfortunately the `x-ms-enum` attribute is optional.  It was added as a means for RPs to explicitly control the name.  In addition, a lot of older swaggers had been exempt from being fixed for various reasons (mostly due to cost).  However, now that we're making a bigger push to fix lingering issues perhaps we can get this kind of issue fixed.

**Comment by ArcturusZhang** [comment]
One of the news is that the compute team is deprecating the problematic `container-services` swagger in the `compute` RP (because it now has it own directory in the swagger repo), therefore for this particular case, from compute api-version 2020-12-01, they will not include this in any newer api-versions.

But I am not quite sure whether this issue also exists in other RP's swaggers. I will have a conversation with the swagger team today to get more information about this issue.
