### ISSUE TITLE
Creation of connection.go: NewConnectoin misses argument to armcore.NewRPRegistrationPolicy

### ISSUE THREAD

**Issue by scseely** [Azure/autorest.go#578]
The track2 generator creates a file called connection.go. The file contains a method, NewConnection. The call to NewRPRegistrationPolicy is missing an argument (endpoint). 

Today, the line generated here reads:

policies = append(policies, armcore.NewRPRegistrationPolicy(cred, &options.RegisterRPOptions))

It should be

policies = append(policies, armcore.NewRPRegistrationPolicy(endpoint, cred, &options.RegisterRPOptions))

It appears that the change should only be to [src/generator/connection.ts:162](https://github.com/Azure/autorest.go/blob/track2/src/generator/connection.ts#L162)

**Comment by jhendrixMSFT** [comment]
The `armcore.NewRPRegistrationPolicy()` is only applicable to ARM services and is enabled implicitly via the `armcore.Connection` (all this is enabled when `azure-arm:true` is set).  We forgot to remove this from codegen when we switched to using `armcore.Connection`.

**Comment by ArcturusZhang** [comment]
@jhendrixMSFT this issue should have been fixed by #579 , maybe we need to close this issue?

**Comment by jhendrixMSFT** [comment]
I will close once we have a new generator with the fix available (trying to wrap up the naming fixes).

**Comment by jhendrixMSFT** [comment]
Fixed in v4.0.0-preview.14
