### ISSUE TITLE
[Feature Idea] Improve Error Experience by writing out CodeModel/Configuration

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.go#646]
In autorest.csharp we improved reported issues by writing out our code model and configuration settings to disk while crashing and asking for them in reported issues.

https://github.com/Azure/autorest.csharp/pull/1199

Depending on traffic, this might make sense for autorest.go as well.

**Comment by chlowell** [comment]
Closing this because autorest core now has a flag, `--inspector` which writes the code model to disk. We would have to ask people to run `autorest` again with that flag set after a crash, but I think that's reasonable.
