### ISSUE TITLE
Custom marshalling/unmarshalling is broken for types composed of multiple types

### ISSUE THREAD

**Issue by ambientlight** [Azure/autorest.go#652]
@jhendrixMSFT: Follow-up to #638

Run into two issues with generated json logic: 

1. invocations of [marshalInternal](https://github.com/ambientlight/azure-sdk-for-go/blob/d97925c0dc464aa445862e5de620e41b80d389d5/services/preview/maps/2.0/creator/models.go#L630) are generated with parameters passed, however the [definition: marshalInternal](https://github.com/ambientlight/azure-sdk-for-go/blob/d97925c0dc464aa445862e5de620e41b80d389d5/services/preview/maps/2.0/creator/models.go#L660-L666) takes(probably no longer) no parameter.
2. [unmarshalGeoJSONFeatureCollectionClassification](https://github.com/ambientlight/azure-sdk-for-go/blob/d97925c0dc464aa445862e5de620e41b80d389d5/services/preview/maps/2.0/creator/models.go#L168) seem no longer present, with [unmarshalGeoJSONObjectClassification](https://github.com/ambientlight/azure-sdk-for-go/blob/d97925c0dc464aa445862e5de620e41b80d389d5/services/preview/maps/2.0/creator/polymorphic_helpers.go#L61) probably should be used instead.

Source: 
https://github.com/ambientlight/azure-rest-api-specs/blob/experiment-scripts/specification/maps/data-plane/Creator/readme.md

**Autorest invocation**:
```
autorest --go --track2 --use=@autorest/go@4.0.0-preview.22 specification/maps/data-plane/Creator/readme.md --go-sdk-folder=../azure-sdk-for-go --multiapi
AutoRest code generation utility [cli version: 3.2.3; node: v14.17.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: 3.4.3.
   Loading AutoRest core      '/home/ambientlight/.autorest/@autorest_core@3.4.3/node_modules/@autorest/core/dist' (3.4.3)
INFORMATION: > Loading AutoRest extension '@autorest/go' (4.0.0-preview.22->4.0.0-preview.22)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.2->4.19.2)
Processing batch task - {"tag":"2.0-preview"} .
INFORMATION: > Loading AutoRest extension '@autorest/go' (4.0.0-preview.22->4.0.0-preview.22)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.2->4.19.2)

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
[9.28 s] Generation Complete
```

**Golang:** 1.16.5
**Platform:** WSL2/Ubuntu 20.04

**To reproduce**:
```
git clone -b experiment-scripts https://github.com/ambientlight/azure-rest-api-specs.git
cd azure-rest-api-specs
./gen_go.sh
```

**Comment by jhendrixMSFT** [comment]
Part of the problem here is that we don't correctly support the case where a type is composed of multiple types.
```json
"GeoJsonFeature": {
  "description": "A valid `GeoJSON Feature` object type. Please refer to [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.2) for details.",
  "x-ms-discriminator-value": "Feature",
  "type": "object",
  "allOf": [
    {
      "$ref": "#/definitions/GeoJsonObject"
    },
    {
      "$ref": "#/definitions/GeoJsonFeatureData"
    }
  ]
},
```

The above currently generates the broken code you linked to.  A fixed version of the codegen might look something like this.
```go
func (g GeoJSONFeature) MarshalJSON() ([]byte, error) {
	objectMap1 := g.GeoJSONObject.marshalInternal(GeoJSONObjectTypeGeoJSONFeature)
	objectMap2 := g.GeoJSONFeatureData.marshalInternal()
	for key, val := range objectMap2 {
		objectMap1[key] = val
	}
	return json.Marshal(objectMap1)
}
```

**Comment by jhendrixMSFT** [comment]
@ambientlight can you clarify what the intent here is (i.e. what comes over the wire).
```json
"GeoJsonFeatureCollection": {
  "description": "A valid `GeoJSON FeatureCollection` object type. Please refer to [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.3) for details.",
  "x-ms-discriminator-value": "FeatureCollection",
  "type": "object",
  "allOf": [
    {
      "$ref": "#/definitions/GeoJsonObject"
    },
    {
      "$ref": "#/definitions/GeoJsonFeatureCollectionData"
    }
  ]
},
```

**Comment by ambientlight** [comment]
GeoJSONObject is a definition reused for type property in GeoJSON spec. It defines type enum. A combination with `x-ms-discriminator-value` allows to lock-down this GeoJSONObject defined 'type' property to constant `FeatureCollection`.
For reference, typescript generation produces the following types:

```ts
export interface GeoJsonObject {
  /** Polymorphic discriminator, which specifies the different types this object can be */
  type:
    | "GeoJsonGeometry"
    | "Feature"
    | "FeatureCollection"
    | "FeatureCollection"
    | "Point"
    | "MultiPoint"
    | "LineString"
    | "MultiLineString"
    | "Polygon"
    | "MultiPolygon"
    | "GeometryCollection";
}

export type GeoJsonFeature = GeoJsonObject & GeoJsonFeatureData & {
  /** Polymorphic discriminator, which specifies the different types this object can be */
  type: "Feature";
};

export interface GeoJsonFeatureCollectionData {
  /** Contains a list of valid `GeoJSON Feature` objects. */
  features: GeoJsonFeature[];
}

export type GeoJsonFeatureCollection = GeoJsonObject & GeoJsonFeatureCollectionData & {
  /** Polymorphic discriminator, which specifies the different types this object can be */
  type: "FeatureCollection";
};
```

**Comment by ambientlight** [comment]
@jhendrixMSFT: to add, the marshalling / unmarshaling issue appears only for multiple embedded struct members. 

Single embedding like at:

```go
type BooleanTypeStyleRule struct {
	StyleObject
	// REQUIRED; Boolean style rules.
	Rules []*BooleanRuleObject `json:"rules,omitempty"`
}
```

generates `MarshalJSON()`/`UnmarshalJSON()` correctly

**Comment by jhendrixMSFT** [comment]
Fixed in preview.28

**Comment by ambientlight** [comment]
@jhendrixMSFT: Sorry, missed your comment, will send a PR to fix the invalid discriminator, thanks for the fix.
