### ISSUE TITLE
Rename `--export-clients` to `--public-clients` for consistency with other languages

### ISSUE THREAD

**Issue by ambientlight** [Azure/autorest.go#653]
@jhendrixMSFT: Follow-up to #638

I am using:

```
autorest --go --track2 --use=@autorest/go@4.0.0-preview.22 specification/maps/data-plane/Creator/readme.md --go-sdk-folder=../azure-sdk-for-go --multiapi
```
for generation. However this generates client types not exposed 
 outside (lowercased).  Example: [alias_client.go](https://github.com/ambientlight/azure-sdk-for-go/blob/d97925c0dc464aa445862e5de620e41b80d389d5/services/preview/maps/2.0/creator/alias_client.go#L20-L22)
 
I am not sure if I am missing something but there should be a way to generate them as public in autorest (instead of something like renameAll and adding Track1-like NewClient scaffold manually). C# autorest provides --public-clients parameter for this, is there anything similar here?

**Comment by ambientlight** [comment]
Found `--export-clients` in [.scripts/regeneration](https://github.com/Azure/autorest.go/blob/track2/.scripts/regeneration.js) which works. Is there any documentation available regarding those available parameters?

**Comment by jhendrixMSFT** [comment]
For data-plane, the default is to generate internal clients.  The reason is that we expect the vast majority of data-plane packages to include hand-written client code (only ARM ships 100% codegen).

I believe if you run `autorest --use=@autorest/go@4.0.0-preview.22 --help` it will dump the switches for Go code generation.

We can consider renaming `--export-clients` to be consistent with other languages, I will follow up with the team about this.

**Comment by ambientlight** [comment]
@jhendrixMSFT: great, thanks!

> For data-plane, the default is to generate internal clients. The reason is that we expect the vast majority of data-plane packages to include hand-written client code (only ARM ships 100% codegen).
Thanks, curious, is this language-specific?, or do you know whether generally for other tear1 languages we are also expected to write client code scaffolds for Track2 codegen?

**Comment by jhendrixMSFT** [comment]
I believe this is uniform across all languages.

**Comment by jhendrixMSFT** [comment]
"Export" is the correct terminology for Go, the other languages use public.  We've documented the switch and its function now.
