### ISSUE TITLE
Use error types specified in swagger

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#662]
Most, if not all, data-plane swaggers define their own error type which is different from the ARM ServiceError type.  Here's an example.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6/graphrbac.json#L1852
While we generate a type for this we don't actually use it during error handling and as a result the actual error information is lost (note the loss has been somewhat mitigated in https://github.com/Azure/go-autorest/pull/292).

**Comment by chamons** [comment]
So I took a look at this, and I think it's either more complex than I expected or I'm missing something (maybe it is correct to return error and not *GraphError, and this is another issue?)

Given the example I posted it generates:

```
func (client *SignedInUserClient) Get(ctx context.Context, options *SignedInUserGetOptions) (SignedInUserGetResponse, error) {
	req, err := client.getCreateRequest(ctx, options)
	if err != nil {
		return SignedInUserGetResponse{}, err
	}
	resp, err := client.con.Pipeline().Do(req)
	if err != nil {
		return SignedInUserGetResponse{}, err
	}
	if !resp.HasStatusCode(http.StatusOK) {
		return SignedInUserGetResponse{}, client.getHandleError(resp)
	}
	return SignedInUserGetResponse{RawResponse: resp.Response}, nil
}

func (client *SignedInUserClient) getCreateRequest(ctx context.Context, options *SignedInUserGetOptions) (*azcore.Request, error) ...
func (client *SignedInUserClient) getHandleError(resp *azcore.Response) error ...
```

I can convert the top level Get to return a `*GraphError`, however `client.getCreateRequest`, `con.Pipeline().Do(req)`, and `client.getHandleError(resp)` all today return error. I can fix those up, but at some point we're going to get multiple `error` returning methods and have to convert or wrap.

Or is this issue saying we should return something different from:

```
func (client *SignedInUserClient) getHandleError(resp *azcore.Response) error {
```

This is the start of my work, and auto "compile" test showing what I originally thought the work should be and a mostly wrong codegen change that changes the top level error type:

https://gist.github.com/chamons/a083b91e91209b3715275667a83c5d24

**Comment by jhendrixMSFT** [comment]
This has been implemented in track 2, we won't be back-porting to track 1.
