### ISSUE TITLE
Generated enum names are not stable and additions can force renames

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.go#668]
As noted in https://github.com/Azure/autorest.go/issues/666 we are generating names such as PossibleEnum4Values and PossibleEnum5Values in go when processing some swagger files.

Steps to reproduce
- Generate https://gist.github.com/chamons/390b238c83a5a2851f9d3698cbc55e3c with autorest.go
- Modify the swagger file to include an operation alphabetically sooner in path, such as https://gist.github.com/chamons/ae0ce82b8c4cd7a76f7eb834c20942c3 which also contains enums
- Compare the generated code:

```
@@ -41,27 +73,27 @@ func (c Get0ItemsItem) ToPtr() *Get0ItemsItem {
 type Head0ItemsItem string

 const (
-       Head0ItemsItemContentType Head0ItemsItem = "content_type"
-       Head0ItemsItemEtag Head0ItemsItem = "etag"
-       Head0ItemsItemKey Head0ItemsItem = "key"
-       Head0ItemsItemLabel Head0ItemsItem = "label"
-       Head0ItemsItemLastModified Head0ItemsItem = "last_modified"
-       Head0ItemsItemLocked Head0ItemsItem = "locked"
-       Head0ItemsItemTags Head0ItemsItem = "tags"
-       Head0ItemsItemValue Head0ItemsItem = "value"
+       Head0ItemsItemA Head0ItemsItem = "a"
+       Head0ItemsItemB Head0ItemsItem = "b"
+       Head0ItemsItemC Head0ItemsItem = "c"
+       Head0ItemsItemD Head0ItemsItem = "d"
+       Head0ItemsItemE Head0ItemsItem = "e"
+       Head0ItemsItemF Head0ItemsItem = "f"
+       Head0ItemsItemG Head0ItemsItem = "g"
+       Head0ItemsItemH Head0ItemsItem = "h"
 )

 // PossibleHead0ItemsItemValues returns the possible values for the Head0ItemsItem const type.
 func PossibleHead0ItemsItemValues() []Head0ItemsItem {
        return []Head0ItemsItem{
-               Head0ItemsItemContentType,
-               Head0ItemsItemEtag,
-               Head0ItemsItemKey,
-               Head0ItemsItemLabel,
-               Head0ItemsItemLastModified,
-               Head0ItemsItemLocked,
-               Head0ItemsItemTags,
-               Head0ItemsItemValue,
+               Head0ItemsItemA,
+               Head0ItemsItemB,
+               Head0ItemsItemC,
+               Head0ItemsItemD,
+               Head0ItemsItemE,
+               Head0ItemsItemF,
+               Head0ItemsItemG,
+               Head0ItemsItemH,
        }
 }
```

The ordering in enums is not stable. Adding a new operation group can cause all existing enums to break.

**Comment by chamons** [comment]
This is extra annoying as we don't have a great customization platform to map the enums or prevent their generation.

Could we use x-ms-name here?

**Comment by chamons** [comment]
I have an example started here: https://github.com/Azure/autorest.go/compare/track2...chamons:issue_668?expand=1

**Comment by jhendrixMSFT** [comment]
This is an artifact of M4 behavior, we can't (at the code generator level) control this.

It's part of a larger conversation about enum definitions omitting x-ms-enum annotations. See here for some of that conversation.
