### ISSUE TITLE
Default branch is track2, Rename track2 branch to main

### ISSUE THREAD

**Issue by RickWinter** [Azure/autorest.go#694]
The track2 generator should be the main branch.

- [x] Rename master -> legacy
- [x] Rename track2 -> main
- [x] Set main as default branch
- [ ] Update documentation for where track1 and track2 generators reside

**Comment by jhendrixMSFT** [comment]
@benbp could you help with this when you have some time?  I no longer have admin on this repo.

**Comment by benbp** [comment]
@jhendrixMSFT Happy to help. I can also make you admin temporarily if you'd prefer that.

**Comment by jhendrixMSFT** [comment]
@benpb if you have some time today please go ahead.
