### ISSUE TITLE
Generated methods reference missing client fields

### ISSUE THREAD

**Issue by chlowell** [Azure/autorest.go#699]
Track 2 data plane clients generated from [this Service Bus spec](
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/sb_dataplane_namespace/specification/servicebus/data-plane/servicebus-swagger.json) lack `apiVersion` fields referenced by methods:

```go
type entityClient struct {
	con *connection
}

func (client *entityClient) deleteCreateRequest(...) (*policy.Request, error) {
	...
	if client.apiVersion != nil {
		reqQP.Set("api-version", "2017_04")
	}
	...
}
```

**Comment by jhendrixMSFT** [comment]
I looked into this, we have a weird corner-case here.

This is similar to single-value enums that are `x-ms-enum modelAsString:false`.  The value is considered a constant by M4, so it should generate no parameter and have its value be embedded in the code.

Where it gets weird is for constants that are marked as `required:false`.  What this means is that the value doesn't _have_ to be sent, but if it is, it can _only_ be the constant value.

You can see an instance of this correctly working for method params [here](https://github.com/Azure/autorest.go/blob/track2/test/compute/2019-12-01/armcompute/zz_generated_dedicatedhosts_client.go#L247-L249).  Unfortunately, we don't properly handle this for client params.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming `preview.32`
