### ISSUE TITLE
Refactor data plane constructors

### ISSUE THREAD

**Issue by chlowell** [Azure/autorest.go#717]
- [x] upgrade to azcore v0.20.0
- [ ] remove Connection, merging it into the client
- [ ] new client constructor should take a pipeline

So the simple case, a client with no host params, would look like this:
```go
type FooClient struct {
    ep string
    pl runtime.Pipeline
}

func NewFooClient(endpoint string, pipeline runtime.Pipeline) *FooClient
```

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming `preview.32` release.
