### ISSUE TITLE
Stop generating modeled error types

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#730]
The Azure contract for error responses is the HTTP status code and an error code, usually provided via `x-ms-error-code` in the response, however in some cases it's in the body.  Any content in the body is for extra context but is subject to change.  Given this, we should stop generating models for the error types specified in swagger.

**Comment by jhendrixMSFT** [comment]
Ok this will work something like this.

`azcore` will contain an `ErrorResponse` interface (maybe a type, will see).

```go
type ErrorResponse interface {
  ErrorCode() string
  StatusCode() int
  RawResponse() *http.Response
}
```

We will stop generating error models.  Instead, we'll call into `azcore` to return an error that conforms to the `ErrorResponse` interface.

The `Error` method on the error will return rich information, basically the same info that you'd see for request/response logging.

**Comment by jhendrixMSFT** [comment]
Some M4 bugs prevent emitting error types in some cases.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming preview.36

**Comment by ArcturusZhang** [comment]
Hey @jhendrixMSFT in some circumstances, the error definitions in swagger might cause duplicate schema errors, since they are recursive types (at least one property is of its own type). I reported this to the modeler here: https://github.com/Azure/autorest/issues/4397

Do you think this change could resolve this? (I think not)

**Comment by jhendrixMSFT** [comment]
No but it shouldn't be a problem.  I believe we already have such generated code.  Or are you saying it's still an issue?

**Comment by jhendrixMSFT** [comment]
This was backed out in https://github.com/Azure/autorest.go/pull/773
