### ISSUE TITLE
Any type marshal problem

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#736]
Marshal of `any` type param will fail when param is assigned with basic type.
e.g., RP: automation, swagger: [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2F31efd7108fe0fcccb69d6b3d4054c648565e767b%2Fspecification%2Fautomation%2Fresource-manager%2FMicrosoft.Automation%2Fstable%2F2019-06-01%2Fschedule.json%23L391-L393&data=04%7C01%7Cchenjieshi%40microsoft.com%7Cf7229e3d22da4bd36dad08d9b39488e3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637738272828564686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8XsEAEGj9JJW3byptKnaFa8c4gAjA8rId%2BUU1ejDLFg%3D&reserved=0), code generated: [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-go%2Fblob%2Fe6b06d2dd24f6ef9ae69fcf2e424d60a77fe3d57%2Fsdk%2Fresourcemanager%2Fautomation%2Farmautomation%2Fzz_generated_schedule_client.go%23L89&data=04%7C01%7Cchenjieshi%40microsoft.com%7Cf7229e3d22da4bd36dad08d9b39488e3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637738272828564686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Cgh9Gg1PX5jjC6du4%2FY3DIM46au0sf0xoJH7faZvpE8%3D&reserved=0), marshal panic position: [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-go%2Fblob%2Fe6b06d2dd24f6ef9ae69fcf2e424d60a77fe3d57%2Fsdk%2Fresourcemanager%2Fautomation%2Farmautomation%2Fzz_generated_models.go%23L4718&data=04%7C01%7Cchenjieshi%40microsoft.com%7Cf7229e3d22da4bd36dad08d9b39488e3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637738272828564686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TvKJcn%2BiVx21Z%2FFpxLHkJm9%2FkJKQaGWH8sS8Xr8dwyM%3D&reserved=0), assignment example: Interval: 1

**Comment by jhendrixMSFT** [comment]
Fixed in preview.32
