### ISSUE TITLE
Unmarshall problem for struct with two embedded params

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#737]
For the struct with two embedded params and both with a custom unmarshall function, unmarshall of parent struct will fail for ambiguous selector of unmarshall functions.
e.g., RP: cdn, swagger: [link](https://github.com/Azure/azure-rest-api-specs/blob/b22180c6a1bed2d181e0b9e846e1f935cfcdb38d/specification/cdn/resource-manager/Microsoft.Cdn/stable/2020-09-01/afdx.json#L2422), code generated: [link](https://github.com/Azure/azure-sdk-for-go/blob/dc35a6aee53f2417e115bd123a7a07ca6050260c/sdk/resourcemanager/cdn/armcdn/zz_generated_models.go#L4547-L4550)
May no need if flatten all the `allof`.

**Comment by jhendrixMSFT** [comment]
This will be fixed via https://github.com/Azure/autorest.go/issues/732.
