### ISSUE TITLE
Unmarshall  of LRO operation response problem

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#738]
If an operation is LRO and the response is a polymorphism type directly, the unmarshall type passed into the `PollUntilDone` function is an inner `xxxClassification`, not the `xxxResult` which will cause failure.
The [swagger](https://github.com/Azure/azure-rest-api-specs/blob/37d690709ce4639bd0aafe7f4a5f5856f2bef624/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2021-08-27/kusto.json#L3150-L3155) which just shows the LRO response type. The generated code for operation: `DataConnections_CreateOrUpdate` will fail when poll result. It seems `&respType.DataConnectionClassification` should be `&respType.DataConnectionCreateOrUpdateResult`.

**Comment by jhendrixMSFT** [comment]
Fixed in preview.32
