### ISSUE TITLE
Multiple media types looks broken in some cases

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#752]
E.g. in `mediatypesgroup`, operation `BinaryBodyWithThreeContentTypes` enum only has two types and hard-coded handling of `text` media type.  Also looks like response handlers will need to conditionally read their appropriate response based on the returned content-type.

**Comment by chlowell** [comment]
Looked into this a little, here's what I learned:
- the generated ContentType1 enum has only two types, for application/json and /octet-stream
- ContentType1 is generated from a sealed-choice schema having only those two choice values

That's odd given the JSON:
```json
"/mediatypes/binaryBodyThreeContentTypes": {
      "post": {
        "description": "...",
        "operationId": "binaryBodyWithThreeContentTypes",
        "consumes": ["application/octet-stream", "text/plain", "application/json"],
```
I notice that after changing "text/plain" to something like "application/foo", the model has a sealed-choice schema with all 3 choices. Is the modeler filtering or choking on text types?

**Comment by jhendrixMSFT** [comment]
It's a good question.  I haven't had time to dig deeply into this.  Also, there is talk of reworking how these operations are handled.  See https://gist.github.com/timotheeguerin/10f0dc3cf722949fd573c7f6241f0cce for more info.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming preview.38
