### ISSUE TITLE
Logic for additional properties: dictionary type with `object` type value

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#756]
We found many swagger examples (e.g. [swagger](https://github.com/Azure/azure-rest-api-specs/blob/d8242e83bad59e45d5bb1dad769a185504f5fde3/specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2020-07-01/appplatform.json#L3543-L3549), [example](https://github.com/Azure/azure-rest-api-specs/blob/d8242e83bad59e45d5bb1dad769a185504f5fde3/specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2020-07-01/examples/Bindings_CreateOrUpdate.json#L7-L10)) set value with primary type like string or integer for the `dictionary` type with `object` type value. The latest codegen will set such dictionary type with map[string][string]interface{} as m4 model it with any-object. It will cause marshal/unmarshall failure. The root cause is the wrong swagger definition. But other language's SDK use special logic for such type's code generation. We should decide how we can handle such issues in GO SDK: 1. change codegen logic or 2. use directive to rewrite all the wrong definition and then fix swagger one by one.

**Comment by jhendrixMSFT** [comment]
The current thinking is that we'll require the service teams to fix their affected swagger.  Will update as more info is available.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming preview.36 release.
