### ISSUE TITLE
Do we introduce the `ListComplete` function in track 2 SDK?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.go#765]
We have a `ListComplete` function if the corresponding `List` function is pageable, providing an iterator to iterate over all the pages using only one loop (regular pageable result requires two loops, one of them is looping over the pages, and the other is looping over the values inside one page).
Do we want that in track 2? This will only add methods therefore I believe if we want to do this, we could do it even after GA

**Comment by jhendrixMSFT** [comment]
No plans at this time.  If we get customer asks, we can consider adding it.  Also, I think that with generics, customers should be able to easily write an iterator (or we might want to write one in azcore).
