### ISSUE TITLE
Omit unused model will cause model misssing

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#771]
When using preview.36 codegen, some models will missing due to the new `omit unused model` feature. Swagger is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/datafactory/resource-manager/readme.go.md). Struct `TypeConversionSettings` will missing.

**Comment by jhendrixMSFT** [comment]
This feature has only been partially implemented, specifically just for error types.  Also, I can't find anything with the name `TypeConversionSettings` in the linked swagger.  Can you please clarify?

**Comment by tadelesh** [comment]
@jhendrixMSFT `TypeConversionSettings` is defined in a separated [file](https://github.com/Azure/azure-rest-api-specs/blob/6a6928f0212c20965ea1faf538cbec8ca6e2e31e/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L5138-L5167) and is used by `TabularTranslator` defined [here](https://github.com/Azure/azure-rest-api-specs/blob/6a6928f0212c20965ea1faf538cbec8ca6e2e31e/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L5099-L5137). All the two models will be generated with v35. But `TypeConversionSettings` is missing with v36.

**Comment by jhendrixMSFT** [comment]
Thanks for clarifying.  This type is a field in `TabularTranslator` which is a discriminated type.  While we have logic to preserve them, we need to propagate that to all child types.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming preview.38 release.
