### ISSUE TITLE
Lack of `strings` input in some case

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#778]
I happened to meet an compiling issue when generating sdk code with this [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/authorization/resource-manager/readme.md). It seems we need to add `strings` to the `imports` before this [line](https://github.com/Azure/autorest.go/blob/2a1bcf3b856e580849ca731efa4c9b2fcdc0965a/src/generator/operations.ts#L799).

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming preview.37
