### ISSUE TITLE
Autorest.go - preview 37

### ISSUE THREAD

**Issue by mohsha-msft** [Azure/autorest.go#796]
When generating code with Autorest.go-37, the `handleResponse()` method does not return back http.Response.

```golang
func (client *blockBlobClient) stageBlockHandleResponse(resp *http.Response) (blockBlobClientStageBlockResponse, error) {
   result := blockBlobClientStageBlockResponse{}
   ...
}
```

I re-ran the same config with autorest.go-35 and I can see it.

```golang
func (client *BlockBlobClient) stageBlockHandleResponse(resp *http.Response) (BlockBlobClientStageBlockResponse, error) {
   result := BlockBlobClientStageBlockResponse{RawResponse: resp}
   ...

}
type BlockBlobClientCommitBlockListResponse struct {
   BlockBlobClientCommitBlockListResult
   // RawResponse contains the underlying HTTP response.
   RawResponse *http.Response
}
```

I have not investigated completely whether this will be a problem or not but we're not returning `Status` and  `StatusCode` from the handleResponse() method and that's certainly a problem.

**Comment by mohsha-msft** [comment]
Mitigation so far: To use Autorest Version 35

**Comment by jhendrixMSFT** [comment]
Closing as I believe the questions have been answered.
