### ISSUE TITLE
Stop generating module name and version constants for data-plane

### ISSUE THREAD

**Issue by chlowell** [Azure/autorest.go#825]
`ModuleName` and `ModuleVersion` aren't needed anymore because data-plane clients don't create their own pipelines. We can stop generating these constants and leave user-agent configuration up to handwritten code. Doing this in a non-breaking fashion might take some thought. I suppose we could make `module-version` optional?

**Comment by RickWinter** [comment]
I see there is a fix for this.  I'm wondering though if we really want this behavior.  Having the generator handle it would make it less likely that individuals get creative in naming or forget to write the two values.

**Comment by RickWinter** [comment]
Good points.  I don't want to be hand editing generated code.  We could have the version.go file have only these two constants and require that to be written by hand (or process) seperate from the autorest generator?

**Comment by jhendrixMSFT** [comment]
Yeah we can do that.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming `v4.0.0` release.
