### ISSUE TITLE
Better solution for optional body param

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#831]
This discussion is started from a .Net customize implementation of code generation. For `PATCH` operation, if there is an existed body param which is not required (e.g., [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2021-07-12/desktopvirtualization.json#L1791)), .Net will always treat it as required. The reason is from semantic view, `PATCH` of resources should always have the body (if not, why we should call `PATCH` operation). So, we discussed it a little bit offline and come with two problems:
1. Should all the body param in `PATCH` operation be required? Is it a swagger issue? If so, we think it should be resolved from swagger side, adding some lint rule and fix the existed problem.
2. For Go, we put all the optional param in the optional envelop. For some `POST` or `PATCH` operation, if there is no required body param, it will be a little weird that the operation only has query params and user need to set the actual entity from optional envelop. Should we handle body param specifically?

Open for discussions. @jhendrixMSFT @RickWinter @mikekistler @JeffreyRichter @ArcturusZhang @lirenhe

**Comment by JeffreyRichter** [comment]
When is it not the case?
A PUT would always pass a body; not optional as this is the resource being created/replaced
A PATCH would always pass a body as this is the resource being created/updated
A POST to create a resource would always pass a body as this is the resource being created
A POST to execute an action may or may not pass a body
A DELETE would never pass a body
A GET would never pass a body but always return one (the resource).

**Comment by jhendrixMSFT** [comment]
Here's the example Chenjie provided.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2021-07-12/desktopvirtualization.json#L1787-L1795

**Comment by JeffreyRichter** [comment]
This is a patch so the body is required. Probably, the swagger should change but sdks should all treat this as mandatory anyway as there is no value to executing a patch without a body

**Comment by mikekistler** [comment]
There are cases where an operation supports an optional request body -- but these are rare. Not for PATCH, and PUT also seems very unlikely but technically I suppose it could happen. But definitely for POST.  So the tests for POST make sense.  We could choose not to support optional bodies on PATCH or PUT but then we should fail the generation with a good error message and not try to paper over this.

**Comment by jhendrixMSFT** [comment]
I would also prefer the approach to error out instead of magically fixing it.  Of course, it means that we'll eventually get the question "it works in $LANGUAGE but not Go, why?"  We already know .NET went down this path, I don't know about the other languages.

**Comment by tadelesh** [comment]
I agree we should fix it in swagger if it is a wrong definition. And if optional body is by service design, I prefer to set it as an explicit method param.

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming `preview.43`
