### ISSUE TITLE
fields marked as azure:ro are always silently removed from the body when sending a request

### ISSUE THREAD

**Issue by serbrech** [Azure/autorest.go#843]
This confused us. we were expecting the body to match what is passed to the client.
The `azure:ro` fields are removed from the request body, and we cannot opt-out of this.

From an api implementer perspective, and considering ARM resource model, sending the readonly fields is valid, as long as they are unchanged. the service accepts a PUT with the readonly fields set, and verifies that they are unchanged.

I think it's a safe default to strip them from the request payload, but an option to opt-out of this behavior would be welcome.

Either at the client level, or at the request level.

For our particular use cases, setting the option at the client level is enough.

**Comment by serbrech** [comment]
alternatively, we could have an option to make the client treat this as error, so that we at least get some feedback that the request was bad.

right now, our client code is re-implementing the readonly validation (checking that we match the target) so that we reject bad requests, instead of having the request work, but unknowingly having properties stripped from the request.

It encourages sloppy programming.

**Comment by jhendrixMSFT** [comment]
We are hoping to remove this stripping of RO fields in the near future.  We just need to ensure that RPaaS-based services don't break.

**Comment by serbrech** [comment]
If you add a flag to opt-in (or opt-out) of that behavior, we would adopt it right away. We are already generating our own sdk for internal use for this reason.
