### ISSUE TITLE
Plugin 'commonmarker' not found

### ISSUE THREAD

**Issue by AndrewCS149** [Azure/autorest.go#844]
OS: Win 11
Autorest/core: 3.8.4
autorest.go: 2.1.188

When attempting to generate the SDK for Go, I receive the error below. 

This is the command I run 
```
AUTOrest --input-file=./automanage.json --output-folder=C:\Users\User\path\to\go\sdk --go --v3
```

```
AutoRest code generation utility [cli version: 3.6.1; node: v17.9.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.2.0.
info    |    Loading AutoRest core      'C:\Users\andrsmith\.autorest\@autorestcore@3.8.4\nodemodules\@autorest\core\dist' (3.8.4)
info    |    Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47->2.1.188)
info    |    Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
fatal   | Process() cancelled due to failure
error   |   Error: Plugin 'commonmarker' not found.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
```

Any help clarifying this issue would be greatly appreciated!

**Comment by mirusky** [comment]
Same problem here, looks like is only when trying to use openapi v3

**Comment by jgruber** [comment]
Piling on... Trying to use --v3 and --go getting the same error.

autorest  --version

AutoRest code generation utility [cli version: 3.6.1; node: v16.15.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.8.4        /home/jgruber/.autorest/@autorest_core@3.8.4
 extension  @autorest/modelerfour                    4.23.5       /home/jgruber/.autorest/@autorest_modelerfour@4.23.5
 extension  @autorest/typescript                     6.0.0-rc.1   /home/jgruber/.autorest/@autorest_typescript@6.0.0-rc.1
 extension  @microsoft.azure/autorest.go             2.1.188      /home/jgruber/.autorest/@microsoft.azure_autorest.go@2.1.188
 extension  @microsoft.azure/autorest.modeler        2.3.38       /home/jgruber/.autorest/@microsoft.azure_autorest.modeler@2.3.38

**Comment by jhendrixMSFT** [comment]
This is the old version of the Go code generator which is on life support.  Is this intentional?  If you update to the latest autorest core `autorest --latest` it will grab the `v4` code generator by default.

**Comment by jhendrixMSFT** [comment]
Closing as stale. Please ping back if there's still a problem.
