### ISSUE TITLE
Always generate 64 precision number to prevent breaking changes

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#864]
For DPG, there exists a rule of always generating 64 precision number for LLC code to prevent possible breaking changes when service change some param/property type from 32 precision to 64 precision.
Current codegen generates code according to the user defined precision. We could opt-in always generate int64/float64.

**Comment by tadelesh** [comment]
Add @JeffreyRichter @jhendrixMSFT for discussion.

**Comment by jhendrixMSFT** [comment]
Do we have any data on how often this kind of breaking change happens?

**Comment by JeffreyRichter** [comment]
It is extremely rare. The best example fo when it did happen is when the max size of a blob changed.
64-bit integers can be painful to work with: more size, slower, as an array index, etc. I personally feel that this is rare enough that it is better to keep the 32-bit ints.

**Comment by tadelesh** [comment]
This choice will also influence CADL support (CADL has `int32`, `int64`, `float32`, `float64`). I've confirmed with other compiled languages: .NET decided to follow the defined precision while Java will always use `long` for `int` and double for `float`. Since it should be a rare situation (I can't even find an example), and I agree that 32-bit number could be benefit for memory and speed, I think we will follow user-defined precision for Go codegen. cc @mikekistler
