### ISSUE TITLE
Add client ctor with credential support if swagger provide security definitions

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#867]
For most auto-generated LLC packages, they have clear security definitions to indicate how to get credential when using the service (some examples: [#1](https://github.com/Azure/azure-rest-api-specs/blob/81cd88a080c4bf4bb251afbe62892a6e220cb2b4/specification/cognitiveservices/data-plane/Language/stable/2022-05-01/analyzeconversations-authoring.json#L8), [#2](https://github.com/Azure/azure-rest-api-specs/blob/81cd88a080c4bf4bb251afbe62892a6e220cb2b4/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.0/speechtotext.json#L5628), [#3](https://github.com/Azure/azure-rest-api-specs/blob/81cd88a080c4bf4bb251afbe62892a6e220cb2b4/specification/maps/data-plane/Microsoft.Maps/FeatureState/preview/2.0/featurestate.json#L23)).
In order to provide a more friendly client and reduce manual work for DPG, I'd like to auto generate the ctor with credential according to the swagger.
Regarding there will be multiple security definitions for one client, the client ctor will use security definitions name as suffix, such as `NewFeatureStateClientWithAADTokenCredential`, `NewFeatureStateClientWithSharedKeyCredential`, `NewFeatureStateClientWithSasTokenCredential`.
Also, a new `KeyCredential` and `KeyCredentialPolicy` will be added to `azcore`. 
This is somehow a DPG feature and also will resolve this [issue](https://github.com/Azure/autorest.go/issues/822).
Any concern? @jhendrixMSFT  @JeffreyRichter

**Comment by JeffreyRichter** [comment]
I do not think you can ultimately be successful with this, which is why we have not done it already.
First, we are assuming that all Azure services will support TokenCredential now and so we do want to auto-generate ctors for this and because we (Azure) want customers to use this cred primarily, we name this ctor NewFeatureStateClient; we do NOT add the WithAADTokenCredential suffix but this ctor does take a TokenCredentail.

Second, most new Azure services will use TokenCred as the only auth mechanism and so we'll get pretty far with code-gen'ing this ctor.

Third, you can't auto-gen SharedKey or SAS creds because what services do with these varies and it's not in the swagger. For example, Storage requires both of these creds to create strings to sign and how to construct the string is not defined in the swagger so it must be manually written. And because the algorithm is service-specific, it must live in the service's package and not in the core package.

**Comment by jhendrixMSFT** [comment]
At present, the only ctor we generate for data-plane is one that takes a pipeline.  Clearly, we don't want to ship like this.

In swagger we currently support token and shared key credentials.  We can certainly change data-plane codegen to emit the correct token credential constructor (with the "good" name) when specified.

For shared key, if we end up with a `NamedKeyCredential` type in `azcore` we can also emit this constructor.  However, as Jeff pointed out, the underlying implementation varies by service so there will still be some amount of hand-written code necessary to make it work.  What would be ideal in this situation is to emit code in such a way that the plumbing is hooked up but it won't actually compile until the appropriate named key policy is implemented.

Finally, how do we want to handle the case when no authentication type is specified in the swagger?  My preference would be to stop doing what we do now (i.e. emit ctor that takes a pipeline) and just emit _no_ ctor.  This would require that implementors provide one.

**Comment by JeffreyRichter** [comment]
Yes, I agree: emit no ctor and write it by hand.

**Comment by tadelesh** [comment]
I agree with Joel's suggestions. If swagger specifics the auth, then we could generate the ctor (e.g., purview, cognitive service), if not, we do nothing (app configuration, key vault, storage). And if the key credential is not a simple get set, we still need to add some hand-written code. 
It will be useful for DPG as all the releases will be handled by service team and we only do the tooling support.
I think the only problem is the ctor naming. It is easy when only one auth defined. But one spec could have multi security definitions. We could set first as default and add suffix for the followings. But it will again depend on the swagger author to not involve any breaks with the sequence.

**Comment by JeffreyRichter** [comment]
A ctor without a credential (NewClient, for example) always takes a TokenCredential - our code generator can always produce this ctor.

Other ctors always have the credential name (NewClientWithSharedKeyCredential, for example) - I do not believe we can code generate these other ctors because there is usually not enough info in the swagger to do it right.

**Comment by jhendrixMSFT** [comment]
Only if it's specified in the spec though, yes?  Put another way, do all services support AAD authentication?

**Comment by JeffreyRichter** [comment]
How are credentials specified in the spec?

**Comment by tadelesh** [comment]
@JeffreyRichter Here are some examples: [#1](https://github.com/Azure/azure-rest-api-specs/blob/81cd88a080c4bf4bb251afbe62892a6e220cb2b4/specification/cognitiveservices/data-plane/Language/stable/2022-05-01/analyzeconversations-authoring.json#L8), [#2](https://github.com/Azure/azure-rest-api-specs/blob/81cd88a080c4bf4bb251afbe62892a6e220cb2b4/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.0/speechtotext.json#L5628), [#3](https://github.com/Azure/azure-rest-api-specs/blob/81cd88a080c4bf4bb251afbe62892a6e220cb2b4/specification/maps/data-plane/Microsoft.Maps/FeatureState/preview/2.0/featurestate.json#L23)

**Comment by tadelesh** [comment]
> Only if it's specified in the spec though, yes? Put another way, do all services support AAD authentication?

I think so. No credential specified, no ctor. For arm spec, m4 always add AAD auth because of the flag [--azure-arm](https://github.com/Azure/autorest/blob/main/docs/generate/authentication.md#--azure-arm).

**Comment by JeffreyRichter** [comment]
I see the securityDefinitions in the spec (thanks). However, I still do not think you have enough information to actually construct the pipeline with the right policy to make it work correctly (at least in some cases). But, if you think you can, give it a try and we can see if it works.

**Comment by jhendrixMSFT** [comment]
The only authentication types supported at present are OAuth2 and API key (see [docs](https://github.com/Azure/autorest/blob/main/docs/generate/authentication.md)).  For the former we can reliably support this for codegen.  For API keys you are correct that we don't have enough info.  We _can_ emit the ctor but obviously we would be missing the correct pipeline policy to make it work.  So it might not be worth emitting it at all.

Regarding ctor naming, we want to reserve the "good name" for the ctor that takes a token credential.  How do we want to handle the case where a service doesn't support AAD auth at present but adds it later?  i.e. if a service only supports shared key auth, should we still name the ctor `NewClientWithSharedKey()`, reserving the "good name" for later?  I think the answer is yes.

**Comment by JeffreyRichter** [comment]
Yes, the good name is always for AAD whether the service supports it today or not.

**Comment by tadelesh** [comment]
Reopen because we need to rethink about the implementation.

**Comment by tadelesh** [comment]
For `keyvault`, I reviewed the related code with [JS](https://github.com/Azure/azure-sdk-for-js/blob/03e4fa261b21b84293059b1a9461ddd56646c07d/sdk/keyvault/keyvault-keys/src/index.ts#L287) and [Python](https://github.com/Azure/azure-sdk-for-python/blob/f23a72b6e78f0d9ad133ded25537dac0b43d3763/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py#L68).
It seems they all generate the original CTOR of the client and replace them with customized client.
For Go, I think we could also always do the CTOR generation. And for the package that need  existed `export-clients` flag to determine whether we

**Comment by jhendrixMSFT** [comment]
Change will be in `preview.46`.
