### ISSUE TITLE
Opt-in `x-ms-external` behavior change

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#876]
Recent change of this [PR](https://github.com/Azure/autorest.go/pull/862) causes breaking changes of mgmt. modules. Need to fix with opt-in.

**Comment by jhendrixMSFT** [comment]
Can I get more details on this?  What specs are using `x-ms-external` and why do we want to not honor that?

**Comment by tadelesh** [comment]
> Can I get more details on this? What specs are using `x-ms-external` and why do we want to not honor that?

@jhendrixMSFT Some recent releases of mgmt. modules got breaking changes by this:
1. kusto: [PR](https://github.com/Azure/azure-sdk-for-go/pull/19124), [swagger](https://github.com/Azure/azure-rest-api-specs/blob/f70b7953f5d54889cc1825b37ad938342ca93a2e/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2022-07-07/kusto.json#L5636)
2. netapp: [PR](https://github.com/Azure/azure-sdk-for-go/pull/19132), [swagger](https://github.com/Azure/azure-rest-api-specs/blob/0507c3d410681049bb5cd9545b49a7578a91d3d0/specification/netapp/resource-manager/Microsoft.NetApp/stable/2022-05-01/netapp.json#L7291)
3. containerservice: [PR](https://github.com/Azure/azure-sdk-for-go/pull/19111), [swagger](https://github.com/Azure/azure-rest-api-specs/blob/2a07629a9919989375ab04490fb24051f78d1a7c/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-07-01/managedClusters.json#L4787)
