### ISSUE TITLE
Can't generate sub-package for a module if package uses OAuth

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#889]
Introduced in https://github.com/Azure/autorest.go/pull/878

E.g. when generating `azcertificates` as a sub-package for a module (stack profile), we don't want to generate it as a module (i.e. we omit the `--module` and `--module-version` switches). The cited change prevents this due to [this](https://github.com/Azure/autorest.go/blob/main/src/generator/constants.ts#L34) change.

**Comment by tadelesh** [comment]
The reason it is required to generate module and moduleVersion info is that it is required with the telemetry policy. If it is a sub-package, then how shall we set the telemetry policy, using the root module info?

**Comment by tadelesh** [comment]
@jhendrixMSFT Is there any example of the sub-package that generated by code gen?

**Comment by jhendrixMSFT** [comment]
We do this for the autorest [test server tests](https://github.com/Azure/autorest.go/tree/main/test/autorest). Also, I believe you do this in the proposed profiles design for track 2?

**Comment by tadelesh** [comment]
After discussion, we agree that the swagger or m4 model does not contain enough info for OAuth. I'll revert the #878.
