### ISSUE TITLE
nil of any type serialize to null

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#946]
For example, this [model](https://github.com/Azure/azure-sdk-for-go/blob/610f7bd3342f04618e722ce44ca4c99702f2117c/sdk/resourcemanager/compute/armcompute/models.go#L7145) contains any type properties, even no value set to those properties, it will be serialized to `"protectedSettings": null`. It is because the reflect null value judgement [here](https://github.com/Azure/azure-sdk-for-go/blob/610f7bd3342f04618e722ce44ca4c99702f2117c/sdk/resourcemanager/compute/armcompute/models_serde.go#L18852) will not work for any/interface{} type. We may need special logic to handle it.

**Comment by jhendrixMSFT** [comment]
Introduced in https://github.com/Azure/autorest.go/pull/734
