### ISSUE TITLE
Fakes path regex is broken for URL-encoded values

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#961]
https://github.com/Azure/autorest.go/blob/c0de3acc643df1f3180d5d0723c7514692f946eb/packages/autorest.go/src/fake/servers.ts#L475

**Comment by tadelesh** [comment]
@jhendrixMSFT I don't know this problem has been resolved thoroughly. We happened into runtime error dealing with the following url: https://github.com/Azure/azure-rest-api-specs/blob/80c21c17b4a7aa57f637ee594f7cfd653255a7e0/specification/iothub/resource-manager/Microsoft.Devices/preview/2023-06-30-preview/iothub.json#L1084
